# version: "3.7"

services:
  backend:
    container_name: elent-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - NODE_ENV=development
    expose:
      - 3001

  fe-user:
    container_name: "elent-fe-user"
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    expose:
      - 80
    depends_on:
      - backend

  nginx:
    container_name: elent-nginx-client
    image: nginx:alpine
    ports:
      - "80:80"
      # - "27018:27018" # Expose 27018 for MongoDB access
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  redis-data:
    name: redis-data
    driver: local
  mongodb-data:
    name: mongodb-data
    driver: local
